### ISSUE TITLE
macboom pro 11,3

### ISSUE THREAD

**Issue by plasticpippo** [MuertoGB/MacBRTool#2]
so there is no bootrom update for macbook pro 11,3 then?
it is the only one not listed?

**Comment by MuertoGB** [comment]
11,3 == 11,2 firmware.

**Comment by plasticpippo** [comment]
thanks! it thought that was the case, but i learnt in the past it is better not to play "guess" with firmware

**Comment by MuertoGB** [comment]
For future reference, you can always run the updater shell if you're unsure, it will refuse to install if the device is not compatible.
